In [1]:
import os, sys
import numpy as np
import pandas as pd
import dataset

In [2]:
path = "rec2img_masked"
identities = os.listdir(path)
identities_imgs_name = {}
for identity in identities:
    imgs_name = []
    for img_name in os.listdir(os.path.join(path, identity)):
        imgs_name.append(img_name)
    identities_imgs_name[identity] = imgs_name

In [3]:
identities_imgs_name['0_490627']

['0.jpg',
 '0_KN95.jpg',
 '1.jpg',
 '10.jpg',
 '100.jpg',
 '100_KN95.jpg',
 '101.jpg',
 '101_glass.jpg',
 '102.jpg',
 '102_KN95.jpg',
 '104.jpg',
 '104_glass.jpg',
 '105.jpg',
 '105_KN95.jpg',
 '106.jpg',
 '106_gas.jpg',
 '107.jpg',
 '107_KN95.jpg',
 '108.jpg',
 '108_gas.jpg',
 '109.jpg',
 '109_gas.jpg',
 '10_surgical.jpg',
 '11.jpg',
 '110.jpg',
 '110_KN95.jpg',
 '111.jpg',
 '111_KN95.jpg',
 '113.jpg',
 '113_glass.jpg',
 '115.jpg',
 '115_glass.jpg',
 '118.jpg',
 '118_cloth.jpg',
 '11_N95.jpg',
 '12.jpg',
 '120.jpg',
 '120_cloth.jpg',
 '121.jpg',
 '121_glass.jpg',
 '123.jpg',
 '123_surgical.jpg',
 '125.jpg',
 '125_glass.jpg',
 '126.jpg',
 '126_KN95.jpg',
 '127.jpg',
 '127_KN95.jpg',
 '129.jpg',
 '129_N95.jpg',
 '12_gas.jpg',
 '13.jpg',
 '130.jpg',
 '130_gas.jpg',
 '131.jpg',
 '131_cloth.jpg',
 '132.jpg',
 '132_surgical.jpg',
 '133.jpg',
 '133_glass.jpg',
 '134.jpg',
 '134_N95.jpg',
 '135.jpg',
 '135_gas.jpg',
 '136.jpg',
 '136_gas.jpg',
 '137.jpg',
 '137_KN95.jpg',
 '138.jpg',
 '138_gl

In [4]:
for img_name in identities_imgs_name['0_490624']:
    if "_" in img_name:
        print(img_name)

0_surgical.jpg
13_glass.jpg
14_glass.jpg
1_glass.jpg
2_N95.jpg
3_cloth.jpg
4_KN95.jpg
5_cloth.jpg
6_N95.jpg
7_glass.jpg
8_gas.jpg
9_cloth.jpg


In [5]:
masked_identities_imgs_name = {}
for k, v in identities_imgs_name.items():
    masked_imgs = []
    for img in v:
        if "_" in img:
            masked_imgs.append(img)
    masked_identities_imgs_name[k] = masked_imgs

In [6]:
masked_identities_imgs_name['0_490630']

['0_cloth.jpg',
 '101_surgical.jpg',
 '104_N95.jpg',
 '105_glass.jpg',
 '106_surgical.jpg',
 '107_gas.jpg',
 '108_surgical.jpg',
 '109_gas.jpg',
 '110_KN95.jpg',
 '111_surgical.jpg',
 '112_cloth.jpg',
 '113_N95.jpg',
 '115_KN95.jpg',
 '116_gas.jpg',
 '117_N95.jpg',
 '118_N95.jpg',
 '11_cloth.jpg',
 '120_KN95.jpg',
 '121_cloth.jpg',
 '122_cloth.jpg',
 '124_KN95.jpg',
 '125_N95.jpg',
 '126_glass.jpg',
 '127_surgical.jpg',
 '128_KN95.jpg',
 '129_gas.jpg',
 '12_KN95.jpg',
 '130_gas.jpg',
 '132_surgical.jpg',
 '133_surgical.jpg',
 '134_surgical.jpg',
 '135_gas.jpg',
 '136_KN95.jpg',
 '13_cloth.jpg',
 '16_surgical.jpg',
 '17_cloth.jpg',
 '19_N95.jpg',
 '20_gas.jpg',
 '21_surgical.jpg',
 '22_KN95.jpg',
 '23_KN95.jpg',
 '24_surgical.jpg',
 '25_N95.jpg',
 '26_N95.jpg',
 '28_surgical.jpg',
 '29_N95.jpg',
 '2_KN95.jpg',
 '30_N95.jpg',
 '31_glass.jpg',
 '32_glass.jpg',
 '33_glass.jpg',
 '34_glass.jpg',
 '35_KN95.jpg',
 '36_cloth.jpg',
 '37_N95.jpg',
 '3_KN95.jpg',
 '40_KN95.jpg',
 '41_glass.jpg',


In [7]:
# mask: cloth, surgical, glass, N95, gas, KN95, all
def get_identities_imgs_name(path="rec2img_masked", mask=None):
    
    identities = os.listdir(path)
    identities_imgs_name = {}
    for identity in identities:
        imgs_name = []
        for img_name in os.listdir(os.path.join(path, identity)):
            imgs_name.append(img_name)
        identities_imgs_name[identity] = imgs_name
    if mask == None:
        return identities_imgs_name
    
    test_string = "_" if mask == "all" else "_"+mask
    masked_identities_imgs_name = {}
    for k, v in identities_imgs_name.items():
        masked_imgs = []
        for img in v:
            if test_string in img:
                masked_imgs.append(img)
        masked_identities_imgs_name[k] = masked_imgs
    
    return masked_identities_imgs_name

In [8]:
surgical_identities_imgs_name = dataset.get_identities_imgs_name()

In [9]:
res, res2 = dataset.generate_pairs(surgical_identities_imgs_name)

In [10]:
len(res), len(res2)

(10571, 10571)

In [11]:
res2

array([['0_490624/13_glass.jpg', '0_493772/2.jpg'],
       ['0_490625/244.jpg', '0_500202/19.jpg'],
       ['0_490626/64.jpg', '0_492044/18_gas.jpg'],
       ...,
       ['0_501193/8.jpg', '0_493146/44.jpg'],
       ['0_501194/16_N95.jpg', '0_491403/8.jpg'],
       ['0_501195/41_cloth.jpg', '0_495105/1.jpg']], dtype='<U25')

In [12]:
def write_pairs(identities_pairs, identities_pairs_not_same, output="out.txt"):
    with open(output, "w") as f:
        for i in range(len(identities_pairs)):
            f.write(identities_pairs[i][0] + " " + identities_pairs[i][1] + " 1")
            f.write('\n')
        
        for i in range(len(identities_pairs_not_same)):
            f.write(identities_pairs_not_same[i][0] + " " + identities_pairs_not_same[i][1] + " 0")
            f.write('\n')

In [14]:
write_pairs(res, res2, "pairs_webfaceOCC.txt")

In [26]:
a = np.arange(100)
b = np.repeat(np.arange(10), 10)
a, b

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]))

In [29]:
r = a + b
rs = np.split(r, 10)
arrs = []
for arr in rs:
    arrs.append(np.sort(arr)[::-1][:5])
arrs

[array([9, 8, 7, 6, 5]),
 array([20, 19, 18, 17, 16]),
 array([31, 30, 29, 28, 27]),
 array([42, 41, 40, 39, 38]),
 array([53, 52, 51, 50, 49]),
 array([64, 63, 62, 61, 60]),
 array([75, 74, 73, 72, 71]),
 array([86, 85, 84, 83, 82]),
 array([97, 96, 95, 94, 93]),
 array([108, 107, 106, 105, 104])]

In [4]:
#np.argpartition(a, -4)[-4:] return n top indices
df_pairs = pd.read_csv("out.txt", sep=" ", header=None, names=["img_name1", "img_name2", "label"])
df_pairs.head()

img_name1                img_name2  label
0    0_490624_4.jpg  0_490624_0_surgical.jpg      1
1   0_490625_93.jpg          0_490625_81.jpg      1
2    0_490626_2.jpg          0_490626_56.jpg      1
3  0_490627_338.jpg     0_490627_109_gas.jpg      1
4    0_490628_9.jpg          0_490628_48.jpg      1

In [7]:
name = "0_490624_4.jpg"
split_name = name.split("_")
"_".join(split_name[:-1]) + "/" + split_name[-1]

'0_490624/4.jpg'

In [ ]:
dataset.generate_file_with_all_identities_names("rec2img_masked", "all_img_names.txt")

In [2]:
imgs = dataset.get_identities_imgs_name()
imgs

{'0_490624': ['0.jpg',
  '0_surgical.jpg',
  '1.jpg',
  '13.jpg',
  '13_glass.jpg',
  '14.jpg',
  '14_glass.jpg',
  '1_glass.jpg',
  '2.jpg',
  '2_N95.jpg',
  '3.jpg',
  '3_cloth.jpg',
  '4.jpg',
  '4_KN95.jpg',
  '5.jpg',
  '5_cloth.jpg',
  '6.jpg',
  '6_N95.jpg',
  '7.jpg',
  '7_glass.jpg',
  '8.jpg',
  '8_gas.jpg',
  '9.jpg',
  '9_cloth.jpg'],
 '0_490625': ['0.jpg',
  '0_N95.jpg',
  '1.jpg',
  '10.jpg',
  '100.jpg',
  '100_KN95.jpg',
  '101.jpg',
  '101_cloth.jpg',
  '102.jpg',
  '102_surgical.jpg',
  '103.jpg',
  '103_gas.jpg',
  '104.jpg',
  '104_N95.jpg',
  '105.jpg',
  '105_gas.jpg',
  '106.jpg',
  '106_surgical.jpg',
  '107.jpg',
  '107_KN95.jpg',
  '108.jpg',
  '108_N95.jpg',
  '109.jpg',
  '109_surgical.jpg',
  '10_KN95.jpg',
  '11.jpg',
  '110.jpg',
  '110_glass.jpg',
  '111.jpg',
  '111_KN95.jpg',
  '112.jpg',
  '112_KN95.jpg',
  '113.jpg',
  '113_cloth.jpg',
  '114.jpg',
  '114_gas.jpg',
  '115.jpg',
  '115_KN95.jpg',
  '116.jpg',
  '116_cloth.jpg',
  '117.jpg',
  '117_KN9

In [3]:
res = [(img, id) for id, imgs in imgs.items() for img in imgs]
res

[('0.jpg', '0_490624'),
 ('0_surgical.jpg', '0_490624'),
 ('1.jpg', '0_490624'),
 ('13.jpg', '0_490624'),
 ('13_glass.jpg', '0_490624'),
 ('14.jpg', '0_490624'),
 ('14_glass.jpg', '0_490624'),
 ('1_glass.jpg', '0_490624'),
 ('2.jpg', '0_490624'),
 ('2_N95.jpg', '0_490624'),
 ('3.jpg', '0_490624'),
 ('3_cloth.jpg', '0_490624'),
 ('4.jpg', '0_490624'),
 ('4_KN95.jpg', '0_490624'),
 ('5.jpg', '0_490624'),
 ('5_cloth.jpg', '0_490624'),
 ('6.jpg', '0_490624'),
 ('6_N95.jpg', '0_490624'),
 ('7.jpg', '0_490624'),
 ('7_glass.jpg', '0_490624'),
 ('8.jpg', '0_490624'),
 ('8_gas.jpg', '0_490624'),
 ('9.jpg', '0_490624'),
 ('9_cloth.jpg', '0_490624'),
 ('0.jpg', '0_490625'),
 ('0_N95.jpg', '0_490625'),
 ('1.jpg', '0_490625'),
 ('10.jpg', '0_490625'),
 ('100.jpg', '0_490625'),
 ('100_KN95.jpg', '0_490625'),
 ('101.jpg', '0_490625'),
 ('101_cloth.jpg', '0_490625'),
 ('102.jpg', '0_490625'),
 ('102_surgical.jpg', '0_490625'),
 ('103.jpg', '0_490625'),
 ('103_gas.jpg', '0_490625'),
 ('104.jpg', '0_490

In [5]:
pd.DataFrame(res, columns=["img_name", "img_id"])

img_name    img_id
0                0.jpg  0_490624
1       0_surgical.jpg  0_490624
2                1.jpg  0_490624
3               13.jpg  0_490624
4         13_glass.jpg  0_490624
...                ...       ...
804699     6_glass.jpg  0_501195
804700           7.jpg  0_501195
804701     7_cloth.jpg  0_501195
804702           8.jpg  0_501195
804703       8_gas.jpg  0_501195

[804704 rows x 2 columns]

In [10]:
map_id_newid = dict(zip(imgs.keys(), range(len(imgs))))
res = [(img, map_id_newid[id]) for id, imgs in imgs.items() for img in imgs]
res[-10:]

[('50_glass.jpg', 10571),
 ('51.jpg', 10571),
 ('51_glass.jpg', 10571),
 ('5_surgical.jpg', 10571),
 ('6.jpg', 10571),
 ('6_glass.jpg', 10571),
 ('7.jpg', 10571),
 ('7_cloth.jpg', 10571),
 ('8.jpg', 10571),
 ('8_gas.jpg', 10571)]

In [2]:
dataset.generate_probe_gallery_set("all_img_names.txt", "gallery_set_original2.txt", "prob_set_surgical_mask2.txt", "original", "surgical")

70
103
204
301
379
502
507
559
566
600
608
652
662
722
736
791
827
829
850
910
928
932
962
982
1037
1072
1144
1182
1274
1311
1349
1352
1377
1381
1393
1394
1405
1408
1423
1432
1438
1445
1449
1464
1471
1487
1502
1509
1515
1518
1571
1581
1604
1615
1616
1681
1698
1701
1717
1720
1721
1723
1750
1752
1781
1814
1845
1874
1875
1882
1892
1899
1912
1917
1929
1971
2051
2055
2058
2071
2087
2115
2161
2186
2187
2193
2213
2214
2239
2242
2246
2310
2324
2339
2343
2373
2381
2395
2409
2443
2456
2470
2490
2496
2515
2536
2540
2550
2585
2587
2620
2621
2665
2675
2698
2718
2746
2747
2764
2780
2823
2832
2838
2895
2927
2937
2942
2953
2955
3001
3026
3027
3039
3061
3093
3101
3102
3122
3162
3197
3201
3210
3228
3294
3363
3369
3406
3422
3429
3443
3454
3544
3559
3562
3564
3642
3682
3694
3750
3785
3794
3796
3799
3848
3859
3876
3891
3963
3967
3972
3987
4034
4057
4069
4123
4126
4130
4209
4243
4253
4280
4282
4289
4361
4368
4377
4380
4383
4426
4479
4528
4532
4587
4605
4607
4625
4633
4666
4680
4697
4733
4738
4748
4752
4757
